"""Violations module — independent module for tracking municipal violations.

This is intentionally separate from the Complaints module: a violation is a
formally-recorded breach of municipal regulations (building, occupancy,
hygiene, etc.) that follows a legal/administrative workflow distinct from a
citizen complaint.
"""
import enum

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Enum as SQLEnum,
    Float,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.core.database import Base
from app.models.enum_utils import enum_values


class ViolationType(str, enum.Enum):
    BUILDING = "building"
    OCCUPANCY = "occupancy"
    MARKET = "market"
    HYGIENE = "hygiene"
    ROAD = "road"
    ENVIRONMENT = "environment"
    PUBLIC_PROPERTY = "public_property"
    OTHER = "other"


class ViolationSeverity(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ViolationStatus(str, enum.Enum):
    NEW = "new"
    UNDER_REVIEW = "under_review"
    INSPECTION_REQUIRED = "inspection_required"
    VIOLATION_CONFIRMED = "violation_confirmed"
    NOTICE_SENT = "notice_sent"
    FINED = "fined"
    RESOLVED = "resolved"
    REJECTED = "rejected"
    REFERRED_TO_LEGAL = "referred_to_legal"


class Violation(Base):
    __tablename__ = "violations"

    id = Column(Integer, primary_key=True, index=True)

    # Human-readable identifier, e.g. VIO-2026-0001. Generated by the API.
    violation_number = Column(String(40), unique=True, nullable=False, index=True)

    title = Column(String(200), nullable=False)
    description = Column(Text, nullable=False)

    violation_type = Column(
        SQLEnum(
            ViolationType,
            name="violationtype",
            values_callable=enum_values,
            validate_strings=True,
        ),
        nullable=False,
        index=True,
    )
    severity = Column(
        SQLEnum(
            ViolationSeverity,
            name="violationseverity",
            values_callable=enum_values,
            validate_strings=True,
        ),
        nullable=False,
        default=ViolationSeverity.MEDIUM,
        index=True,
    )
    status = Column(
        SQLEnum(
            ViolationStatus,
            name="violationstatus",
            values_callable=enum_values,
            validate_strings=True,
        ),
        nullable=False,
        default=ViolationStatus.NEW,
        index=True,
    )

    # Organizational scope. Both point at the same organization_units table
    # (municipality/district). district_id (when set) is a child of
    # municipality_id. The denormalized org_unit_id is used by the existing
    # scope_query() RBAC helper and is set automatically by the API to the
    # most specific known unit (district_id, falling back to municipality_id).
    municipality_id = Column(
        Integer, ForeignKey("organization_units.id"), nullable=True, index=True
    )
    district_id = Column(
        Integer, ForeignKey("organization_units.id"), nullable=True, index=True
    )
    org_unit_id = Column(
        Integer, ForeignKey("organization_units.id"), nullable=True, index=True
    )

    reported_by_user_id = Column(
        Integer, ForeignKey("users.id"), nullable=True, index=True
    )
    assigned_to_user_id = Column(
        Integer, ForeignKey("users.id"), nullable=True, index=True
    )

    # Optional cross-references to related records. Nullable on purpose: a
    # violation may originate from a citizen complaint or a field task, but
    # most are self-initiated by inspectors.
    related_complaint_id = Column(
        Integer, ForeignKey("complaints.id"), nullable=True, index=True
    )
    related_task_id = Column(
        Integer, ForeignKey("tasks.id"), nullable=True, index=True
    )

    location_text = Column(Text, nullable=True)
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)

    legal_reference = Column(String(255), nullable=True)
    fine_amount = Column(Numeric(12, 2), nullable=True)
    deadline_date = Column(DateTime(timezone=True), nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)

    is_active = Column(Boolean, nullable=False, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    reported_by = relationship("User", foreign_keys=[reported_by_user_id])
    assigned_to = relationship("User", foreign_keys=[assigned_to_user_id])
    municipality = relationship("OrganizationUnit", foreign_keys=[municipality_id])
    district = relationship("OrganizationUnit", foreign_keys=[district_id])
